ARG OS_VERSION=7
FROM centos:${OS_VERSION}

ARG OS_VERSION=7
ARG CONDOR_URL=http://prod-exe.icecube.wisc.edu/htcondor/condor-8.7.2-x86_64_RedHat${OS_VERSION}-stripped.tar.gz
ARG CONDOR_VERSION=8.7.2

RUN yum -y install \
    cron \
    epel-release \
    freetype \
    glibc-static \
    libgomp \
    libstdc++-static \
    perl \
    openssl \
    wget

RUN yum -y groupinstall 'Development Tools'

RUN wget http://smarden.org/runit/runit-2.1.2.tar.gz \
 && tar xvzf runit-2.1.2.tar.gz \
 && cd admin/runit-2.1.2/ \
 && ./package/install \
 && cd / \
 && rm -f runit-2.1.2.tar.gz

RUN useradd condor \
 && su -c "wget ${CONDOR_URL}" - condor \
 && su -c "mkdir ~/condor-${CONDOR_VERSION}; cd ~/condor-${CONDOR_VERSION}; mkdir local" - condor \
 && su -c "cd ~/condor-${CONDOR_VERSION}; tar -z -x -f ~/condor-${CONDOR_VERSION}-*-stripped.tar.gz" - condor \
 && su -c "cd ~/condor-${CONDOR_VERSION}; ./condor-${CONDOR_VERSION}-*-stripped/condor_install --local-dir /home/condor/condor-${CONDOR_VERSION}/local --make-personal-condor" - condor \
 && rm -f /home/condor/condor-${CONDOR_VERSION}-*-stripped.tar.gz \
 && chmod 755 /home/condor \
 && chmod 755 /home/condor/condor-${CONDOR_VERSION}/condor.sh
 
RUN yum -y install \
    attr \
    autofs \
    fuse \
    fuse-libs \
    gawk \
    gdb \
    policycoreutils-python \
 && rpm -ivh https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/cvmfs-config-default-1.4-1.noarch.rpm \
 && if [ $OS_VERSION -eq 7 ]; then CVMFS_RPM_NAME=cvmfs-2.3.5-1.el7.centos.x86_64.rpm; elif [ $OS_VERSION -eq 6 ]; then CVMFS_RPM_NAME=cvmfs-2.3.5-1.el6.x86_64.rpm; fi \
 && rpm -ivh --nodeps https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.3.5/${CVMFS_RPM_NAME} \
 && echo "user_allow_other" >> /etc/fuse.conf \
 && echo "/cvmfs /etc/auto.cvmfs" >> /etc/auto.master \
 && echo "CVMFS_REPOSITORIES='icecube.opensciencegrid.org'" > /etc/cvmfs/default.local \
 && echo "CVMFS_HTTP_PROXY='DIRECT'" >> /etc/cvmfs/default.local

RUN useradd pyglidein \
 && chmod 777 /home/pyglidein \
 && yum -y install python-pip \
 && pip install --upgrade setuptools

RUN pip install requests

RUN mkdir -p /data/log/condor \
 && mkdir /data/log/pyglidein_server

RUN if [ $OS_VERSION -eq 7 ]; then yum -y groupremove 'Development Tools'; fi

COPY server/root/ /
COPY pyglidein-* /
RUN pip install /pyglidein-*

ENTRYPOINT /usr/local/bin/runsvdir -P /etc/sv
