#!/bin/bash
exec 2>&1
cd /home/pyglidein
# Changing the permissions of the secrets file because its being volumed into the container
chown pyglidein:pyglidein .pyglidein_secrets
chmod 600 .pyglidein_secrets
exec chpst -u pyglidein pyglidein_client --config=/etc/sv/pyglidein_client/pbs_torque_config
